In [1]:
import os
import numpy as np
import pandas as pd 
from tqdm import tqdm_notebook
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
from pandas.plotting import scatter_matrix

import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split

In [2]:
train = pd.read_csv('train.csv')
train.head()

layer_1  layer_2  layer_3  layer_4         0         1         2         3  \
0       10       10       10       10  0.254551  0.258823  0.254659  0.252085   
1       10       10       10       20  0.205062  0.225544  0.217758  0.202169   
2       10       10       10       30  0.189196  0.165869  0.177655  0.156822   
3       10       10       10       40  0.131003  0.120076  0.138975  0.117931   
4       10       10       10       50  0.091033  0.086893  0.108125  0.080405   

          4         5  ...       216       217       218       219       220  \
0  0.247678  0.253614  ...  0.354750  0.369223  0.388184  0.408496  0.414564   
1  0.199633  0.207380  ...  0.557203  0.573656  0.587998  0.612754  0.627825   
2  0.175094  0.177755  ...  0.699864  0.708688  0.721982  0.713464  0.743030   
3  0.130566  0.131262  ...  0.764786  0.763788  0.770017  0.787571  0.778866   
4  0.105917  0.077083  ...  0.786677  0.802271  0.806557  0.799614  0.789333   

        221       222       223       224       225  
0  0.429403  0.419225  0.443250  0.433414  0.465502  
1  0.633393  0.637706  0.625981  0.653231  0.637853  
2  0.741709  0.747743  0.746037  0.737356  0.750391  
3  0.776969  0.774712  0.801526  0.805305  0.784057  
4  0.804087  0.787763  0.794948  0.819105  0.801781  

[5 rows x 230 columns]

In [3]:
num_cols = list(train.select_dtypes(exclude=['object']).columns)
layers = num_cols[0:4]

In [6]:
layers

['layer_1', 'layer_2', 'layer_3', 'layer_4']

In [7]:
X = train.iloc[:,4:]
y1 = train.loc[:, train.columns == 'layer_1']/10
y2 = train.loc[:, train.columns == 'layer_2']/10
y3 = train.loc[:, train.columns == 'layer_3']/10
y4 = train.loc[:, train.columns == 'layer_4']/10

In [17]:
# -11.26나옴
start = time.time()

base = RandomForestRegressor(random_state=0, n_estimators=3)

scores = cross_val_score(base, X, y, cv=3, scoring='neg_mean_absolute_error')
print ("ROC: %.2f (+/- %.2f) [%s]" %(scores.mean(), scores.std(), "Random Forest"))

print("Running time :", time.time() - start, "sec")  # 실행 시간

In [22]:
start = time.time()

base = RandomForestRegressor(random_state=0, n_estimators=10)

scores = cross_val_score(base, X, y, cv=3, scoring='neg_mean_absolute_error')
print ("ROC: %.2f (+/- %.2f) [%s]" %(scores.mean(), scores.std(), "Random Forest"))

print("Running time :", time.time() - start, "sec")  # 실행 시간

ROC: -10.85 (+/- 3.11) [Random Forest]
Running time : 12618.158285856247 sec


In [25]:
# No CV version
import time
from sklearn.ensemble import RandomForestRegressor

start = time.time()

base = RandomForestRegressor(random_state=0, n_estimators=3)
base.fit(X, y2)

print("Running time :", time.time() - start, "sec")  # 실행 시간

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [3]:
test = pd.read_csv('test.csv')

del test["id"]
test.head()

0         1         2         3         4         5         6  \
0  0.535410  0.520775  0.494087  0.465134  0.430339  0.401751  0.355986   
1  0.351099  0.398179  0.413809  0.418529  0.433257  0.455410  0.451065   
2  0.490537  0.435958  0.413428  0.355796  0.335777  0.299944  0.242745   
3  0.051634  0.075802  0.133983  0.154546  0.209387  0.251700  0.287552   
4  0.154031  0.201728  0.270414  0.283799  0.343050  0.340233  0.379244   

          7         8         9  ...       216       217       218       219  \
0  0.326427  0.282340  0.216756  ...  0.748339  0.757575  0.768130  0.777062   
1  0.464230  0.476011  0.477219  ...  0.333931  0.276307  0.211513  0.159223   
2  0.210555  0.180739  0.169717  ...  0.709371  0.746826  0.781436  0.788292   
3  0.333000  0.340617  0.393592  ...  0.075046  0.056651  0.079884  0.147469   
4  0.378511  0.373017  0.364702  ...  0.255070  0.242396  0.271287  0.328828   

        220       221       222       223       224       225  
0  0.769173  0.768253  0.738704  0.739460  0.702139  0.702238  
1  0.110982  0.083130  0.099780  0.145420  0.260501  0.343857  
2  0.828630  0.835166  0.845859  0.846032  0.836724  0.846779  
3  0.213112  0.298096  0.382823  0.489381  0.562383  0.599247  
4  0.397950  0.486436  0.530573  0.582752  0.637296  0.637238  

[5 rows x 226 columns]

In [29]:
pred2 = base.predict(test)
pred2

array([24.66666667, 14.        , 18.        , ..., 11.        ,
        5.        ,  2.        ])

In [30]:
# No CV version
import time
from sklearn.ensemble import RandomForestRegressor

start = time.time()

base = RandomForestRegressor(random_state=0, n_estimators=3)
base.fit(X, y4)

print("Running time :", time.time() - start, "sec")  # 실행 시간

Running time : 1782.4595866203308 sec


In [31]:
pred4 = base.predict(test)
pred4

array([ 8.33333333, 12.        , 15.66666667, ...,  3.33333333,
       14.33333333,  8.33333333])

### baseline: n_estimator=10

In [32]:
# No CV version
import time
from sklearn.ensemble import RandomForestRegressor

start = time.time()

base_10 = RandomForestRegressor(random_state=0, n_estimators=10)
base_10.fit(X, y2)

print("Running time :", time.time() - start, "sec")  # 실행 시간

Running time : 6875.956134557724 sec


In [33]:
pred2_10 = base_10.predict(test)
pred2_10

array([23.4, 13.2, 17.3, ..., 18.6,  4.5,  1.8])

In [34]:
# No CV version
import time
from sklearn.ensemble import RandomForestRegressor

start = time.time()

base4_10 = RandomForestRegressor(random_state=0, n_estimators=10)
base4_10.fit(X, y4)

print("Running time :", time.time() - start, "sec")  # 실행 시간

Running time : 13919.85361123085 sec


In [35]:
pred4_10 = base4_10.predict(test)
pred4_10

array([ 8.3, 11.2, 15.9, ..., 11.6,  8.2,  7.3])

In [36]:
pred2_10 = pd.DataFrame(pred2_10 * 10)
pred4_10 = pd.DataFrame(pred4_10 * 10)

In [37]:
preds2 = pd.concat([pred2_10, pred4_10],axis=1)

In [38]:
preds2.to_csv('pred2.csv')

### LGBM

In [4]:
import lightgbm as lgbm
from sklearn.model_selection import cross_val_score, train_test_split
from bayes_opt import BayesianOptimization

In [13]:
train_val, valid = train_test_split(train, test_size=0.3, random_state=0)

In [14]:
X_val = train_val.iloc[:,4:]
y1_val = train_val.loc[:, train_val.columns == 'layer_1']/10
y2_val = train_val.loc[:, train_val.columns == 'layer_2']/10
y3_val = train_val.loc[:, train_val.columns == 'layer_3']/10
y4_val = train_val.loc[:, train_val.columns == 'layer_4']/10

X_val_val = valid.iloc[:,4:]
y1_val_val = valid.loc[:, valid.columns == 'layer_1']/10
y2_val_val = valid.loc[:, valid.columns == 'layer_2']/10
y3_val_val = valid.loc[:, valid.columns == 'layer_3']/10
y4_val_val = valid.loc[:, valid.columns == 'layer_4']/10

In [15]:
## LightGBM
import warnings
warnings.filterwarnings('ignore')

d_train = lgbm.Dataset(X_val, y1_val)
d_test = lgbm.Dataset(X_val_val, y1_val_val)

n_folds = 3
random_seed=6

# BayesianOptimization
def lgb_eval(num_leaves, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight):
    params = {'application':'regression',
              'num_iterations': 500 ,
              'learning_rate':0.05,
              'early_stopping_round':100,
              "num_threads" : 20 ,
              'metric':'l1'
             }
    params["num_leaves"] = int(round(num_leaves))
    params['max_depth'] = int(round(max_depth))
    params['lambda_l1'] = max(lambda_l1, 0)
    params['lambda_l2'] = max(lambda_l2, 0)
    params['min_split_gain'] = min_split_gain
    params['min_child_weight'] = min_child_weight
    cv_result = lgbm.cv(params, d_train,
                       nfold=n_folds, seed=random_seed,
                       stratified=False, verbose_eval =200,
                       metrics=['l1']
                        )
    return min(cv_result['l1-mean'])

lgbBO1 = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                        'max_depth': (5, 8.99),
                                        'lambda_l1': (0, 5),
                                        'lambda_l2': (0, 3),
                                        'min_split_gain': (0.001, 0.1),
                                        'min_child_weight': (5, 50)}, random_state=0)
init_round = 5
opt_round = 15
lgbBO1.maximize(init_points=init_round, n_iter=opt_round)

|   iter    |  target   | lambda_l1 | lambda_l2 | max_depth | min_ch... | min_sp... | num_le... |
-------------------------------------------------------------------------------------------------
[200]	cv_agg's l1: 4.86315 + 0.00957146
[400]	cv_agg's l1: 4.17318 + 0.00502523
|  1        |  3.961    |  2.744    |  2.146    |  7.405    |  29.52    |  0.04294  |  37.56    |
[200]	cv_agg's l1: 4.95568 + 0.00391501
[400]	cv_agg's l1: 4.27971 + 0.022752
|  2        |  4.035    |  2.188    |  2.675    |  8.845    |  22.25    |  0.07938  |  35.11    |
[200]	cv_agg's l1: 5.15405 + 0.0137302
[400]	cv_agg's l1: 4.54509 + 0.020049
|  3        |  4.334    |  2.84     |  2.777    |  5.283    |  8.921    |  0.003002 |  41.49    |
[200]	cv_agg's l1: 4.80797 + 0.0134292
[400]	cv_agg's l1: 4.1102 + 0.0125787
|  4        |  3.882    |  3.891    |  2.61     |  8.905    |  40.96    |  0.04669  |  40.39    |
[200]	cv_agg's l1: 4.97637 + 0.0168219
[400]	cv_agg's l1: 4.32027 + 0.0112678
|  5        |  4.109  

In [16]:
lgbBO1.max

{'target': 4.485899044745153,
 'params': {'lambda_l1': 0.0,
  'lambda_l2': 3.0,
  'max_depth': 5.0,
  'min_child_weight': 5.0,
  'min_split_gain': 0.001,
  'num_leaves': 24.0}}

In [17]:
params1 = {'lambda_l1': int(0.0),
          'lambda_l2': int(3.0),
          'max_depth': int(5.0),
          'min_child_weight': int(5.0),
          'min_split_gain': int(0.001),
          'num_leaves': int(24.0)}

d_train_total = lgbm.Dataset(X, y1)

lgb1 = lgbm.train(params1 , d_train_total)
lgb_pred_y1 = lgb1.predict( test )
lgb_pred_y1

In [24]:
lgb_pred_y1 = pd.DataFrame(lgb_pred_y1 * 10)
lgb_pred_y1.to_csv('lgb_pred_y1.csv')

In [25]:
## LightGBM - y2
import warnings
warnings.filterwarnings('ignore')

d_train = lgbm.Dataset(X_val, y2_val)
d_test = lgbm.Dataset(X_val_val, y2_val_val)

n_folds = 3
random_seed=6

# BayesianOptimization
def lgb_eval(num_leaves, max_depth, lambda_l1, lambda_l2, min_split_gain, min_child_weight):
    params = {'application':'regression',
              'num_iterations': 500 ,
              'learning_rate':0.05,
              'early_stopping_round':100,
              "num_threads" : 20 ,
              'metric':'l1'
             }
    params["num_leaves"] = int(round(num_leaves))
    params['max_depth'] = int(round(max_depth))
    params['lambda_l1'] = max(lambda_l1, 0)
    params['lambda_l2'] = max(lambda_l2, 0)
    params['min_split_gain'] = min_split_gain
    params['min_child_weight'] = min_child_weight
    cv_result = lgbm.cv(params, d_train,
                       nfold=n_folds, seed=random_seed,
                       stratified=False, verbose_eval =200,
                       metrics=['l1']
                        )
    return min(cv_result['l1-mean'])

lgbBO2 = BayesianOptimization(lgb_eval, {'num_leaves': (24, 45),
                                        'max_depth': (5, 8.99),
                                        'lambda_l1': (0, 5),
                                        'lambda_l2': (0, 3),
                                        'min_split_gain': (0.001, 0.1),
                                        'min_child_weight': (5, 50)}, random_state=0)
init_round = 5
opt_round = 15
lgbBO2.maximize(init_points=init_round, n_iter=opt_round)

|   iter    |  target   | lambda_l1 | lambda_l2 | max_depth | min_ch... | min_sp... | num_le... |
-------------------------------------------------------------------------------------------------
[200]	cv_agg's l1: 6.08798 + 0.0256737
[400]	cv_agg's l1: 5.73075 + 0.0122503
|  1        |  5.6      |  2.744    |  2.146    |  7.405    |  29.52    |  0.04294  |  37.56    |
[200]	cv_agg's l1: 6.07929 + 0.0101811
[400]	cv_agg's l1: 5.75946 + 0.0176151
|  2        |  5.623    |  2.188    |  2.675    |  8.845    |  22.25    |  0.07938  |  35.11    |
[200]	cv_agg's l1: 6.21155 + 0.00991632
[400]	cv_agg's l1: 5.92794 + 0.0029828
|  3        |  5.825    |  2.84     |  2.777    |  5.283    |  8.921    |  0.003002 |  41.49    |
[200]	cv_agg's l1: 6.05766 + 0.0164542
[400]	cv_agg's l1: 5.67342 + 0.0122309
|  4        |  5.527    |  3.891    |  2.61     |  8.905    |  40.96    |  0.04669  |  40.39    |
[200]	cv_agg's l1: 6.13291 + 0.00894902
[400]	cv_agg's l1: 5.8251 + 0.0114764
|  5        |  5.697 

In [26]:
lgbBO2.max

{'target': 5.891882643811129,
 'params': {'lambda_l1': 5.0,
  'lambda_l2': 0.0,
  'max_depth': 5.0,
  'min_child_weight': 5.0,
  'min_split_gain': 0.001,
  'num_leaves': 24.0}}

In [27]:
params2 = {'lambda_l1': int(5.0),
          'lambda_l2': int(0.0),
          'max_depth': int(5.0),
          'min_child_weight': int(5.0),
          'min_split_gain': int(0.001),
          'num_leaves': int(24.0)}

d_train_total = lgbm.Dataset(X, y2)

lgb2 = lgbm.train(params2 , d_train_total)
lgb_pred_y2 = lgb2.predict( test )
lgb_pred_y2

array([20.31079885, 15.42380454, 16.06380165, ..., 15.08866384,
       10.78714147, 11.51589352])

In [28]:
lgb_pred_y2 = pd.DataFrame(lgb_pred_y2 * 10)
lgb_pred_y2.to_csv('lgb_pred_y2.csv')

### XGBoost

In [5]:
import xgboost as xgb

In [6]:
dtrain = xgb.DMatrix(X, y1)

In [52]:
params = {'n_estimators': 3,'objective': 'reg:linear','eval_metric':'mae', 'silent': 1}
scores = xgb.cv(params, dtrain, num_boost_round=5,verbose_eval=False, nfold=2, metrics = 'mae')

In [53]:
scores

train-mae-mean  train-mae-std  test-mae-mean  test-mae-std
0       10.980198       0.000501      10.983896      0.005826
1        8.840144       0.023163       8.846964      0.024793
2        7.706995       0.060823       7.721520      0.056216
3        7.029834       0.028354       7.050923      0.019483
4        6.616729       0.024814       6.643199      0.009596

In [ ]:
## Xgboost
import warnings
warnings.filterwarnings('ignore')

dtrain = xgb.DMatrix(X, label=y1)

In [11]:
## XGBoost

def xgb_eval(max_depth,
              gamma,
              min_child_weight,
              max_delta_step,
              subsample,
              colsample_bytree):
    params = { 'booster' : 'gbtree',
              'max_depth' : int(max_depth),
              'gamma' : gamma,
              'eta' : 0.1,
              'objective' : 'reg:linear',
              'silent' : True,
              'eval_metric': 'mae',
              'subsample' : max(min(subsample, 1), 0),
              'colsample_bytree' : max(min(colsample_bytree, 1), 0),
              'min_child_weight' : min_child_weight,
              'max_delta_step' : int(max_delta_step),
              'seed' : 1001 }

    cv_result = xgb.cv(
                    params,
                    dtrain,
                    stratified = True,
                    nfold = 3,
                    num_boost_round = 30,
                    verbose_eval = 10,
                    early_stopping_rounds = 20,
                    metrics = "mae")
    return max(cv_result['train-mae-mean'])


In [12]:
xgb_bo1 = BayesianOptimization(xgb_eval, {'max_depth': (2, 8),
                                          'gamma': (0.001),
                                          'min_child_weight': (0, 20),
                                          'max_delta_step': (0, 10),
                                          'subsample': (0.0, 1.0),
                                          'colsample_bytree' :(0.0, 1.0)})

init_round = 2
opt_round = 3
xgb_bo1.maximize(init_points=init_round, n_iter=opt_round)



|   iter    |  target   | colsam... |   gamma   | max_de... | max_depth | min_ch... | subsample |
-------------------------------------------------------------------------------------------------
[0]	train-mae:13.5507+0.00328908	test-mae:13.5525+0.00316964
[10]	train-mae:7.271+0.0212275	test-mae:7.28827+0.0207631
[20]	train-mae:5.9617+0.0217233	test-mae:5.99479+0.0167528
[29]	train-mae:5.49509+0.00567125	test-mae:5.53932+0.0077873
|  1        |  13.55    |  0.2058   |  7.734    |  0.02481  |  7.882    |  18.04    |  0.4877   |
[0]	train-mae:13.5618+0.00105991	test-mae:13.5614+0.00236934
[10]	train-mae:7.43547+0.00982094	test-mae:7.44311+0.0106746
[20]	train-mae:6.22922+0.00394494	test-mae:6.2448+0.00859541
[29]	train-mae:5.79409+0.00992039	test-mae:5.8152+0.0117471
|  2        |  13.56    |  0.2902   |  5.348    |  0.7253   |  6.539    |  9.281    |  0.1153   |
[0]	train-mae:14.0333+4.54606e-06	test-mae:14.0333+4.18994e-06
[10]	train-mae:8.40593+0.00128953	test-mae:8.4063+0.00218509
[2

In [13]:
xgb_bo1.max

{'target': 14.033368666666666,
 'params': {'colsample_bytree': 1.0,
  'gamma': 0.001,
  'max_delta_step': 10.0,
  'max_depth': 8.0,
  'min_child_weight': 0.0,
  'subsample': 1.0}}

In [25]:
# del test['id']
dtest = xgb.DMatrix( test )

In [19]:
params1 = {'colsample_bytree': int(1.0),
          'gamma': int(0.001),
          'max_delta_step': int(10.0),
          'max_depth': int(8.0),
          'min_child_weight': int(0.0),
          'subsample': int(1.0)}

xgb1 = xgb.train(params1 , dtrain)

In [35]:
xgb_pred_y1 = xgb1.predict( dtest )
xgb_pred_y1

array([22.188948,  7.943536, 17.393732, ..., 11.935744,  9.936696,
       10.222967], dtype=float32)

In [21]:
xgb_pred_y1 = pd.DataFrame(xgb_pred_y1 * 10)
xgb_pred_y1.to_csv('xgb_pred_y1.csv')

#### y2

In [24]:
## Xgboost
import warnings
warnings.filterwarnings('ignore')

dtrain = xgb.DMatrix(X, label=y2)

In [25]:
xgb_bo2.max

{'target': 11.533334000000002,
 'params': {'colsample_bytree': 0.29109503084901,
  'gamma': 4.162993661451414,
  'max_delta_step': 2.7444376555691354,
  'max_depth': 4.50404889863046,
  'min_child_weight': 11.12565947123895,
  'subsample': 0.7925704757239624}}

In [44]:
# params1 = {'colsample_bytree': int(1.0),
#           'gamma': int(0.001),
#           'max_delta_step': int(10.0),
#           'max_depth': int(8.0),
#           'min_child_weight': int(0.0),
#           'subsample': int(1.0)}

params2 = {'colsample_bytree': int(1),
          'gamma': int(0.001),
          'max_delta_step': int(10),
          'max_depth': int(8),
          'min_child_weight': int(0.0),
          'subsample': int(1)}

xgb2 = xgb.train(params2 , dtrain)

In [46]:
xgb_pred_y2 = xgb2.predict( dtest )
xgb_pred_y2

array([18.945454, 15.256061, 14.147975, ..., 14.175552, 11.63875 ,
       12.289859], dtype=float32)

In [47]:
xgb_pred_y2 = pd.DataFrame(xgb_pred_y2 * 10)
xgb_pred_y2.to_csv('xgb_pred_y2.csv')

In [48]:
dtrain = xgb.DMatrix(X, label=y3)
xgb3 = xgb.train(params2 , dtrain)
xgb_pred_y3 = xgb3.predict( dtest )
xgb_pred_y3

array([15.422844 , 18.862568 , 19.726646 , ..., 16.5971   , 10.200529 ,
        6.6876884], dtype=float32)

In [49]:
xgb_pred_y3 = pd.DataFrame(xgb_pred_y3 * 10)
xgb_pred_y3.to_csv('xgb_pred_y3.csv')

In [50]:
dtrain = xgb.DMatrix(X, label=y4)
xgb4 = xgb.train(params2 , dtrain)
xgb_pred_y4 = xgb4.predict( dtest )
xgb_pred_y4

array([13.497682, 14.346597, 17.919598, ..., 15.718689, 14.08509 ,
        9.98105 ], dtype=float32)

In [51]:
xgb_pred_y4 = pd.DataFrame(xgb_pred_y4 * 10)
xgb_pred_y4.to_csv('xgb_pred_y4.csv')